#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
SNAPSHOT="contracts/public_api.snapshot"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

cat > "$TMPDIR/public_api_snapshot.go" <<'GO'
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var packages = []string{"errx", "timex", "lifecycx", "retryx", "healthx", "obsx", "validx", "syncx", "versionx", "contracttest"}

func main() {
	root, err := os.Getwd()
	must(err)
	fmt.Println("# github.com/ZoneCNH/kernel public API snapshot")
	fmt.Println("# Generated by scripts/ci/api-diff-check.sh. Update only with API compatibility review.")
	fmt.Println()
	for _, pkg := range packages {
		lines := packageSurface(root, pkg)
		fmt.Printf("package %s\n", pkg)
		for _, line := range lines {
			fmt.Println(line)
		}
		fmt.Println()
	}
}

func packageSurface(root, pkg string) []string {
	set := token.NewFileSet()
	dir := filepath.Join(root, pkg)
	files, err := os.ReadDir(dir)
	must(err)
	var lines []string
	for _, entry := range files {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		path := filepath.Join(dir, name)
		file, err := parser.ParseFile(set, path, nil, parser.ParseComments)
		must(err)
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch s := spec.(type) {
					case *ast.TypeSpec:
						if ast.IsExported(s.Name.Name) {
							lines = append(lines, "type "+s.Name.Name+" "+nodeString(set, s.Type))
						}
					case *ast.ValueSpec:
						for _, name := range s.Names {
							if ast.IsExported(name.Name) {
								lines = append(lines, strings.ToLower(d.Tok.String())+" "+name.Name+valueSpecSuffix(set, s))
							}
						}
					}
				}
			case *ast.FuncDecl:
				if d.Recv == nil {
					if ast.IsExported(d.Name.Name) {
						lines = append(lines, "func "+d.Name.Name+funcTypeString(set, d.Type))
					}
					continue
				}
				receiver := receiverName(d.Recv)
				if receiver != "" && ast.IsExported(receiver) && ast.IsExported(d.Name.Name) {
					lines = append(lines, "method ("+receiver+") "+d.Name.Name+funcTypeString(set, d.Type))
				}
			}
		}
	}
	sort.Strings(lines)
	return lines
}

func valueSpecSuffix(set *token.FileSet, s *ast.ValueSpec) string {
	var parts []string
	if s.Type != nil {
		parts = append(parts, nodeString(set, s.Type))
	}
	if len(s.Values) > 0 {
		var vals []string
		for _, v := range s.Values {
			vals = append(vals, nodeString(set, v))
		}
		parts = append(parts, "= "+strings.Join(vals, ", "))
	}
	if len(parts) == 0 {
		return ""
	}
	return " " + strings.Join(parts, " ")
}

func funcTypeString(set *token.FileSet, ft *ast.FuncType) string {
	text := nodeString(set, ft)
	return strings.TrimPrefix(text, "func")
}

func receiverName(fields *ast.FieldList) string {
	if fields == nil || len(fields.List) != 1 {
		return ""
	}
	switch expr := fields.List[0].Type.(type) {
	case *ast.Ident:
		return expr.Name
	case *ast.StarExpr:
		if ident, ok := expr.X.(*ast.Ident); ok {
			return ident.Name
		}
	}
	return ""
}

func nodeString(set *token.FileSet, node any) string {
	var buf bytes.Buffer
	must(printer.Fprint(&buf, set, node))
	return strings.Join(strings.Fields(buf.String()), " ")
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
GO

GOWORK=off go run "$TMPDIR/public_api_snapshot.go" > "$TMPDIR/current.snapshot"

if [ "${UPDATE_PUBLIC_API_SNAPSHOT:-}" = "1" ]; then
  cp "$TMPDIR/current.snapshot" "$SNAPSHOT"
  echo "updated public API snapshot: $SNAPSHOT"
  exit 0
fi

[ -s "$SNAPSHOT" ] || {
  echo "ERROR: public API snapshot missing: $SNAPSHOT" >&2
  echo "Run UPDATE_PUBLIC_API_SNAPSHOT=1 $0 after compatibility review." >&2
  exit 1
}

if ! diff -u "$SNAPSHOT" "$TMPDIR/current.snapshot"; then
  echo "ERROR: public API drift detected. Update $SNAPSHOT only with API compatibility review." >&2
  exit 1
fi

echo "public API snapshot check passed: $SNAPSHOT"
