#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SNAPSHOT="$ROOT/contracts/public_api.snapshot"
MODE="check"
if [[ "${1:-}" == "--write" ]]; then
  MODE="write"
fi
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT
GEN="$TMPDIR/gen-api-snapshot.go"
OUT="$TMPDIR/public_api.snapshot"
cat > "$GEN" <<'GO'
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var packages = []string{"contextx", "contracttest", "errx", "healthx", "lifecycx", "obsx", "retryx", "shutdownx", "syncx", "timex", "validx", "versionx"}

func main() {
	root := os.Getenv("KERNEL_ROOT")
	if root == "" { panic("KERNEL_ROOT missing") }
	var lines []string
	for _, pkg := range packages {
		lines = append(lines, snapshotPackage(root, pkg)...)
	}
	sort.Strings(lines)
	fmt.Println("# kernel public API snapshot v1")
	fmt.Println("# generated by scripts/ci/api-diff-check.sh --write")
	for _, line := range lines { fmt.Println(line) }
}

func snapshotPackage(root, pkg string) []string {
	path := filepath.Join(root, pkg)
	fset := token.NewFileSet()
	files, err := parser.ParseDir(fset, path, func(info os.FileInfo) bool { return !strings.HasSuffix(info.Name(), "_test.go") }, parser.ParseComments)
	if err != nil { panic(err) }
	parsed, ok := files[pkg]
	if !ok { panic("package not found: " + pkg) }
	var lines []string
	for _, file := range parsed.Files {
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch s := spec.(type) {
					case *ast.TypeSpec:
						if !s.Name.IsExported() { continue }
						lines = append(lines, fmt.Sprintf("type %s.%s %s", pkg, s.Name.Name, expr(fset, s.Type)))
						if st, ok := s.Type.(*ast.StructType); ok {
							for _, field := range st.Fields.List {
								for _, name := range field.Names {
									if !name.IsExported() { continue }
									tag := ""
									if field.Tag != nil { tag = " " + field.Tag.Value }
									lines = append(lines, fmt.Sprintf("field %s.%s.%s %s%s", pkg, s.Name.Name, name.Name, expr(fset, field.Type), tag))
								}
							}
						}
					case *ast.ValueSpec:
						for i, name := range s.Names {
							if !name.IsExported() { continue }
							typ := ""
							if s.Type != nil { typ = " " + expr(fset, s.Type) } else if i < len(s.Values) { typ = " = " + expr(fset, s.Values[i]) }
							kind := "var"
							if d.Tok == token.CONST { kind = "const" }
							lines = append(lines, fmt.Sprintf("%s %s.%s%s", kind, pkg, name.Name, typ))
						}
					}
				}
			case *ast.FuncDecl:
				if !d.Name.IsExported() { continue }
				if d.Recv == nil {
					lines = append(lines, fmt.Sprintf("func %s.%s%s", pkg, d.Name.Name, signature(fset, d.Type)))
					continue
				}
				recv := recvName(fset, d.Recv)
				if recv == "" || !ast.IsExported(recv) { continue }
				lines = append(lines, fmt.Sprintf("method %s.%s.%s%s", pkg, recv, d.Name.Name, signature(fset, d.Type)))
			}
		}
	}
	return lines
}

func signature(fset *token.FileSet, t *ast.FuncType) string {
	params := fieldList(fset, t.Params)
	results := fieldList(fset, t.Results)
	if results == "" { return "(" + params + ")" }
	if strings.Contains(results, ",") || strings.Contains(results, " ") {
		return "(" + params + ") (" + results + ")"
	}
	return "(" + params + ") " + results
}
func fieldList(fset *token.FileSet, fl *ast.FieldList) string {
	if fl == nil || len(fl.List) == 0 { return "" }
	var parts []string
	for _, f := range fl.List {
		typ := expr(fset, f.Type)
		if len(f.Names) == 0 { parts = append(parts, typ); continue }
		for _, n := range f.Names { parts = append(parts, n.Name+" "+typ) }
	}
	return strings.Join(parts, ", ")
}
func recvName(fset *token.FileSet, fl *ast.FieldList) string {
	if fl == nil || len(fl.List) == 0 { return "" }
	switch t := fl.List[0].Type.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		if ident, ok := t.X.(*ast.Ident); ok { return ident.Name }
	}
	return strings.TrimPrefix(expr(fset, fl.List[0].Type), "*")
}
func expr(fset *token.FileSet, node ast.Node) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, node); err != nil { panic(err) }
	return strings.Join(strings.Fields(buf.String()), " ")
}
GO
KERNEL_ROOT="$ROOT" GOWORK=off go run "$GEN" > "$OUT"
if [[ "$MODE" == "write" ]]; then
  cp "$OUT" "$SNAPSHOT"
  echo "api-diff-check: wrote $SNAPSHOT"
  exit 0
fi
[[ -f "$SNAPSHOT" ]] || { echo "api-diff-check: missing $SNAPSHOT; run scripts/ci/api-diff-check.sh --write" >&2; exit 1; }
if ! diff -u "$SNAPSHOT" "$OUT"; then
  echo "api-diff-check: public API drift detected; run scripts/ci/api-diff-check.sh --write after approved API changes" >&2
  exit 1
fi
echo "api-diff-check: ok"
