#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
SNAPSHOT="contracts/public_api.snapshot"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT
GEN="$TMPDIR/public_api_snapshot.go"
OUT="$TMPDIR/public_api.snapshot"

cat > "$GEN" <<'GO'
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

var includeDirs = []string{"contracttest", "errx", "healthx", "lifecycx", "obsx", "retryx", "syncx", "timex", "validx", "versionx"}

func main() {
	var lines []string
	for _, dir := range includeDirs {
		set := token.NewFileSet()
		pkgs, err := parser.ParseDir(set, dir, func(info os.FileInfo) bool {
			name := info.Name()
			return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
		}, parser.ParseComments)
		if err != nil { panic(err) }
		for pkgName, pkg := range pkgs {
			lines = append(lines, "package "+pkgName)
			var files []*ast.File
			for _, f := range pkg.Files { files = append(files, f) }
			sort.Slice(files, func(i, j int) bool { return set.Position(files[i].Pos()).Filename < set.Position(files[j].Pos()).Filename })
			for _, f := range files { collect(set, pkgName, f, &lines) }
		}
	}
	sort.Strings(lines)
	fmt.Println("# Code generated by scripts/ci/api-diff-check.sh; DO NOT EDIT BY HAND.")
	fmt.Println("# Public API snapshot for github.com/ZoneCNH/kernel.")
	for _, line := range lines { fmt.Println(line) }
}

func collect(set *token.FileSet, pkg string, f *ast.File, lines *[]string) {
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if !s.Name.IsExported() { continue }
					*lines = append(*lines, fmt.Sprintf("%s type %s %s", pkg, s.Name.Name, expr(set, s.Type)))
					if st, ok := s.Type.(*ast.StructType); ok { collectStructFields(set, pkg, s.Name.Name, st, lines) }
					if it, ok := s.Type.(*ast.InterfaceType); ok { collectInterfaceMethods(set, pkg, s.Name.Name, it, lines) }
				case *ast.ValueSpec:
					for _, name := range s.Names {
						if !name.IsExported() { continue }
						kind := "var"; if d.Tok == token.CONST { kind = "const" }
						typ := "<inferred>"; if s.Type != nil { typ = expr(set, s.Type) }
						*lines = append(*lines, fmt.Sprintf("%s %s %s %s", pkg, kind, name.Name, typ))
					}
				}
			}
		case *ast.FuncDecl:
			if !d.Name.IsExported() { continue }
			if d.Recv == nil {
				*lines = append(*lines, fmt.Sprintf("%s func %s%s", pkg, d.Name.Name, funcSig(set, d.Type)))
			} else {
				*lines = append(*lines, fmt.Sprintf("%s method %s.%s%s", pkg, recvName(set, d.Recv), d.Name.Name, funcSig(set, d.Type)))
			}
		}
	}
}

func collectStructFields(set *token.FileSet, pkg, typeName string, st *ast.StructType, lines *[]string) {
	for _, field := range st.Fields.List {
		fieldType := expr(set, field.Type)
		jsonTag := ""
		if field.Tag != nil {
			if unq, err := strconv.Unquote(field.Tag.Value); err == nil {
				if tag := reflectTagGet(unq, "json"); tag != "" { jsonTag = " json:" + tag }
			}
		}
		if len(field.Names) == 0 { *lines = append(*lines, fmt.Sprintf("%s field %s.<embedded> %s%s", pkg, typeName, fieldType, jsonTag)); continue }
		for _, name := range field.Names { if name.IsExported() { *lines = append(*lines, fmt.Sprintf("%s field %s.%s %s%s", pkg, typeName, name.Name, fieldType, jsonTag)) } }
	}
}

func collectInterfaceMethods(set *token.FileSet, pkg, typeName string, it *ast.InterfaceType, lines *[]string) {
	for _, field := range it.Methods.List {
		if len(field.Names) == 0 { *lines = append(*lines, fmt.Sprintf("%s interface %s embeds %s", pkg, typeName, expr(set, field.Type))); continue }
		for _, name := range field.Names { if name.IsExported() { *lines = append(*lines, fmt.Sprintf("%s interface %s.%s %s", pkg, typeName, name.Name, expr(set, field.Type))) } }
	}
}

func funcSig(set *token.FileSet, ft *ast.FuncType) string {
	return strings.TrimPrefix(expr(set, ft), "func")
}
func recvName(set *token.FileSet, fl *ast.FieldList) string {
	if fl == nil || len(fl.List) == 0 { return "" }
	s := expr(set, fl.List[0].Type)
	s = strings.TrimPrefix(s, "*")
	return s
}
func expr(set *token.FileSet, e ast.Expr) string {
	var buf bytes.Buffer
	if err := format.Node(&buf, set, e); err != nil { panic(err) }
	return strings.Join(strings.Fields(buf.String()), " ")
}
func reflectTagGet(tag, key string) string {
	for tag != "" {
		tag = strings.TrimLeft(tag, " ")
		if tag == "" { break }
		i := strings.Index(tag, ":")
		if i < 0 { break }
		name := tag[:i]
		tag = tag[i+1:]
		if tag == "" || tag[0] != '"' { break }
		value, rest, ok := scanQuoted(tag)
		if !ok { break }
		if name == key { return value }
		tag = rest
	}
	return ""
}
func scanQuoted(s string) (string, string, bool) {
	for i := 1; i < len(s); i++ {
		if s[i] == '\\' { i++; continue }
		if s[i] == '"' { v, err := strconv.Unquote(s[:i+1]); return v, s[i+1:], err == nil }
	}
	return "", "", false
}

var _ = filepath.Separator
GO

GOWORK=off go run "$GEN" > "$OUT"
if [ "${UPDATE_API_SNAPSHOT:-}" = "1" ]; then
  cp "$OUT" "$SNAPSHOT"
  echo "public API snapshot updated: $SNAPSHOT"
  exit 0
fi
[ -s "$SNAPSHOT" ] || { echo "ERROR: missing $SNAPSHOT (run UPDATE_API_SNAPSHOT=1 scripts/ci/api-diff-check.sh)" >&2; exit 1; }
if ! diff -u "$SNAPSHOT" "$OUT"; then
  echo "ERROR: public API snapshot drift detected" >&2
  echo "Update docs/api.md and run UPDATE_API_SNAPSHOT=1 scripts/ci/api-diff-check.sh for intentional additions." >&2
  echo "Breaking removals/signature changes require governance ADR and version decision." >&2
  exit 1
fi
echo "public API snapshot check passed"
